// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opruamxldzqgiiigrduz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wcnVhbXhsZHpxZ2lpaWdyZHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjI0NDcsImV4cCI6MjA2MjYzODQ0N30.7R62tfBeujwxuGQO5TJQlxEQp1vJm-hPyh5ucWOW1aI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);